apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-v2-deployment
  labels:
    app: webapp-v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp-v2
  template:
    metadata:
      labels:
        app: webapp-v2
      annotations:
        version: "2.0"
    spec:
      containers:
      - name: webapp-v2
        image: clerikc/go-web-app.v2:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"