apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-v2-deployment
  labels:
    app: webapp-v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp-v2
  template:
    metadata:
      labels:
        app: webapp-v2
      annotations:
        version: "2.0"
    spec:
      containers:
      - name: webapp-v2
        image: webapp-local
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"