apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-v2-deployment
  labels:
    app: webapp-v2
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: webapp-v2
  template:
    metadata:
      labels:
        app: webapp-v2
      annotations:
        version: "2.0"
    spec:
    template:
    spec:
      imagePullSecrets:
      - name: ghcr-secret 
      containers:
      - name: webapp-v2
        image: ghcr.io/clerikc/go-web-app.v2:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"