# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: CI/CD Pipeline v2

on:
  push:
    branches: [ main ]
    paths:
      - '**.go'
      - 'Dockerfile'
      - 'static/**'
      - 'k8s/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21
    
    - name: Build
      run: go build -v ./...
    
    - name: Test
      run: go test -v ./...
  
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: clerikc/go-web-app.v2:latest
    
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install kubectl
      uses: azure/setup-kubectl@v3
    
    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl rollout status deployment/webapp-v2-deployment
      env:
        KUBECONFIG: ${{ secrets.KUBE_CONFIG }}