name: CI/CD Pipeline v2

on:
  push:
    branches: [ main ]
    paths:
      - '**.go'
      - 'Dockerfile'
      - 'static/**'
      - 'k8s/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21
    
    - name: Build
      run: go build -v ./...
    
    - name: Test
      run: go test -v ./...
  
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # Авторизация в GHCR
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT_TOKEN }}
    
    # Сборка и загрузка в GHCR с правильным именем репозитория
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.actor }}/go-web-app.v2:latest  # Используем actor

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan ${{ secrets.VM_IP }} >> ~/.ssh/known_hosts
    
    - name: Deploy to VM
      run: |
        scp -r ./k8s ${{ secrets.VM_USER }}@${{ secrets.VM_IP }}:/tmp/
        ssh ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} "
          kubectl apply -f /tmp/k8s/deployment.yaml
          kubectl apply -f /tmp/k8s/service.yaml
          kubectl rollout status deployment/webapp-v2-deployment
        "